// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/gym-card/card.vue')['default']
    Container: typeof import('./src/components/gym-card/container.vue')['default']
    Drawer: typeof import('./src/components/gym-card/drawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImg: typeof import('element-plus/es')['ElImg']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    GymCard: typeof import('./src/components/gym-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPageHeader: typeof import('./src/components/user-page-header/index.vue')['default']
    UserPageLayout: typeof import('./src/components/user-page-layout.vue')['default']
    UserPagePagination: typeof import('./src/components/user-page-pagination/index.vue')['default']
    UserPageTitle: typeof import('./src/components/user-page-title.vue')['default']
  }
}
